### ISSUE TITLE
dear author,could you please update those scripts?thank you very much.

### ISSUE THREAD

**Issue by brioglade** [FMassin/SeismicSource#1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-72ff037a15f5> in <module>()
      8 dc = np.array([0.,0.,0.,1.,0.,0.])
      9 model_example = SeismicSource(dc)
---> 10 model_example.Aki_Richards.plot(wave='P',style='v')

/home/ufo/paddle/SeismicSource/source.py in plot(self, wave, style, comp, ax)
    868         """
    869         # Get radiation pattern
--> 870         G, XYZ = self.radpat(wave)
    871         if comp == None :
    872             if wave in ('Sv', 'Sv wave', 'Sv-wave'):

/home/ufo/paddle/SeismicSource/source.py in radpat(self, wave, obs_cart, obs_sph)
    713         # Get observation points
    714         if obs_sph == 'None':
--> 715             obs_sph = sphere(r=1.,n=1000.)
    716         ## Get unit sphere, or spherical coordinate if given
    717         if obs_cart == 'None' :

/home/ufo/paddle/SeismicSource/source.py in sphere(r, n)
     65     nt = n**(.5-c)
     66 
---> 67     [AZIMUTH,TAKEOFF] = np.meshgrid( np.linspace(0, 2*np.pi, na+1), np.linspace(0, 1*np.pi, nt) )
     68 
     69     RADIUS = np.ones(AZIMUTH.shape)*r

<__array_function__ internals> in linspace(*args, **kwargs)

/home/ufo/anaconda3/envs/obspy/lib/python3.7/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    111 
    112     """
--> 113     num = operator.index(num)
    114     if num < 0:
    115         raise ValueError("Number of samples, %s, must be non-negative." % num)

TypeError: 'float' object cannot be interpreted as an integer

**Comment by FMassin** [comment]
Good morning,

Ok I've fixed it. Make sure you now use Python3... 

Cheers
